Add gcp site creation
k2view/blueprints pull request #29
Opened 2024-01-22 11:00 UTC by vstartse

Added gcp site creation with relevant modules and helm charts

2024-01-25 15:31 UTC, kirilmaz-k2v requested changes

2024-01-25 15:31 UTC, kirilmaz-k2v commented on gcp/terraform/Environments/cloud_site_private/CREATE_PRIVATE_SITE.md
> +5. Certbot installed
Certbot is not Pre-requisites, assume the user have cert

2024-01-25 15:31 UTC, kirilmaz-k2v commented on gcp/terraform/Modules/Kubernetes/admin-service-account/README.md
This user not used anymore, it replaced with the agent, it can be removed or at list make it optional and false by default

2024-01-25 15:31 UTC, kirilmaz-k2v commented on gcp/terraform/Modules/Network/cloud-dns/main.tf
Remove code that not used anymore, if the labels not used it also should be removed from the variables

2024-01-25 15:31 UTC, kirilmaz-k2v commented on gcp/terraform/Modules/Network/subnets/versions.tf
If this code not used anymore remove it

2024-01-25 15:31 UTC, kirilmaz-k2v commented on gcp/terraform/Modules/Network/vpc/variables.tf
Remove defaults that not generic

2024-01-25 15:31 UTC, kirilmaz-k2v commented on helm/grafana-agent/k8s-monitoring/ci/ci-2-values.yaml
Remove not generic defaults

2024-01-25 15:31 UTC, kirilmaz-k2v commented on helm/grafana-agent/k8s-monitoring/ci/ci-integrations-values.yaml
Remove not generic defaults

2024-01-25 15:31 UTC, kirilmaz-k2v commented on helm/grafana-agent/k8s-monitoring/ci/ci-values.yaml
Remove not generic defaults

2024-01-29 11:15 UTC, vstartse commented on gcp/helm/charts/gcp-pd-storage-class/values.yaml
> +region:
done

2024-01-29 11:24 UTC, vstartse commented on gcp/terraform/Environments/cloud_site_private/CREATE_PRIVATE_SITE.md
> +### Configure Site Domain
done

2024-01-29 11:26 UTC, vstartse commented on gcp/terraform/Modules/Kubernetes/admin-service-account/README.md
removed

2024-01-29 11:28 UTC, vstartse commented on gcp/terraform/Modules/Network/cloud-dns/main.tf
removed

2024-01-29 11:34 UTC, vstartse commented on gcp/terraform/Modules/Network/subnets/versions.tf
module removed

2024-01-29 11:34 UTC, vstartse commented on gcp/terraform/Modules/Network/vpc/variables.tf
module removed

2024-01-29 11:35 UTC, vstartse commented on helm/grafana-agent/k8s-monitoring/ci/ci-2-values.yaml
all values are generic

2024-01-29 11:36 UTC, vstartse commented on helm/grafana-agent/k8s-monitoring/ci/ci-integrations-values.yaml
all values are generic

2024-01-29 11:36 UTC, vstartse commented on helm/grafana-agent/k8s-monitoring/ci/ci-values.yaml
all values are generic

2024-02-01 09:05 UTC, merged