fix typos and spelling
k2view/blueprints pull request #90
Opened 2024-11-05 16:26 UTC by kirilmaz-k2v

2024-11-05 17:51 UTC, loayNaser commented
@kirilmaz-k2v why not on the blueprints-dev and also we can use thi PR as a real UC test for the syncing process

2024-11-06 07:16 UTC, itayAlmani1 approved these changes

2024-11-06 07:53 UTC, loayNaser requested changes
you should do this PR at blueprints-dev

2024-12-03 17:02 UTC, kirilmaz-k2v commented
moved to blueprints-dev

2024-12-03 17:02 UTC, closed without merging